### ISSUE TITLE
Stopword Removal Problem

### ISSUE THREAD

**Issue by AarRidho** [har07/PySastrawi#11]
`kalimat = 'Saya dan Kamu adalah Manusia'
stop = stopword.remove(kalimat)
print(stop)
`
Print = Saya Kamu Manusia

`kalimat = 'saya dan kamu adalah Manusia'
stop = stopword.remove(kalimat)
print(stop)`

Print = dan kamu Manusia

Ini memang seperti ini ya? atau cuma saya yang salah tanggap?

**Comment by Frizz925** [comment]
Kayaknya ini bug lama deh. Kalo install lewat pip dapetnya versi 1.0.1 yang masih ada bugnya dan ini udah dibenerin di branch master](https://github.com/har07/PySastrawi/commit/0d7fcdb2ce013339666896763eb9eb20a400cfa3#diff-ac20a7cf929aca421d1bdf6c6ac7f846).

**Comment by AarRidho** [comment]
Saya pip versi 9 bawaan dari installer Python 3.6, mungkin package di pipnya belom update kali ya?

**Comment by Frizz925** [comment]
Saya make pip versi 10 juga kena bug ini. Keknya gara-gara versi terbarunya blom dipublish ke pip.

**Comment by har07** [comment]
@AarRidho @Frizz925 saya sudah publish versi baru, mungkin bisa dicoba: https://pypi.org/project/PySastrawi/1.1.0/
