### ISSUE TITLE
Menambahkan stopword

### ISSUE THREAD

**Issue by rezaagungp** [har07/PySastrawi#9]
saya ingin menanyakan, apakah ada dokumentasi penambahan list stopword. jika belum ada bagaimana cara menambahkan kata ke list stopword.

**Comment by prasastoadi** [comment]
@rezaagungp bisa ditambahkan secara manual pada file [StopWordRemoverFactory.py](https://github.com/har07/PySastrawi/blob/master/src/Sastrawi/StopWordRemover/StopWordRemoverFactory.py)

**Comment by widnyana** [comment]
@prasastoadi apakah memungkinkan untuk mengimplementasi fitur muat stopwords dari file?

**Comment by anggriyulio** [comment]
Tinggal tambah saja list nya, CMIIW baru coba2 🍔 

```
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
 
s = 'Aku pernah mendengar Aisya bercerita bahwa sebenarnya ia tidak terlalu senang dengan kabar perjodohan yang diatur oleh orang tuanya.'
 
#Create factory
stop_factory = StopWordRemoverFactory()
more_stopword = ['dengan', 'ia','bahwa','oleh']
 
# Tambahkan Stopword Baru
data = stop_factory.get_stop_words()+more_stopword
 
stopword = stop_factory.create_stop_word_remover()
print(stopword.remove(s))
```

[source](https://devtrik.com/python/menambah-stopword-pada-python-sastrawi/)

**Comment by arinanda** [comment]
> Tinggal tambah saja list nya, CMIIW baru coba2 🍔
> 
> ```
> from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
>  
> s = 'Aku pernah mendengar Aisya bercerita bahwa sebenarnya ia tidak terlalu senang dengan kabar perjodohan yang diatur oleh orang tuanya.'
>  
> #Create factory
> stop_factory = StopWordRemoverFactory()
> more_stopword = ['dengan', 'ia','bahwa','oleh']
>  
> # Tambahkan Stopword Baru
> data = stop_factory.get_stop_words()+more_stopword
>  
> stopword = stop_factory.create_stop_word_remover()
> print(stopword.remove(s))
> ```
> [source](https://devtrik.com/python/menambah-stopword-pada-python-sastrawi/)

@anggriyulio saya sudah mengikuti cara ini, di file `StopWordRemoverFactory.py` kata yang saya ingin tambahkan berhasil masuk kedalam array, namun kata-kata baru tersebut tidak dihilangkan dari kalimat yang saya masukkan

**Comment by anggriyulio** [comment]
@arinanda Pake pysastrawi versi berapa ? Cara diatas bisa digunakan untuk sastrawi versi 1.1.0 dan sebelumnya. Silahkan baca di [sini](https://github.com/har07/PySastrawi/commit/b31d6f67c24ee78d76d5095d405433f9cc774603)

Untuk versi 1.2.0 coba dengan cara ini 
```
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, StopWordRemover, ArrayDictionary

s = 'Aku pernah mendengar Aisya bercerita bahwa sebenarnya ia tidak terlalu senang dengan kabar perjodohan yang diatur oleh orang tuanya.'

# Ambil Stopword bawaan
stop_factory = StopWordRemoverFactory().get_stop_words()
more_stopword = ['diatur', 'perjodohan']

# Merge stopword
data = stop_factory + more_stopword

dictionary = ArrayDictionary(data)
str = StopWordRemover(dictionary)

print(str.remove(s))

# Aku mendengar Aisya bercerita senang kabar tuanya.
```

**Comment by rannbaraku** [comment]
bagaimana cara menggunakan metode berbeda sari library, seperti list Tala, maupun Doly
